// src/types.ts
/**
 * Core types and interfaces used across the application.
 *
 * Strong typing is enforced here so other modules can depend on
 * explicit contracts instead of `any`.
 */

import type { spawn } from "bun";

export type Status = "running" | "completed" | "stopped" | "error";

/**
 * Download represents a single managed livestream download.
 *
 * - id: opaque string id (generated by uid())
 * - user: tiktok username
 * - status: current lifecycle state
 * - process: underlying Bun spawn return type (optional)
 * - startTime: moment when this run started
 * - outputDir: output directory used for the run
 */
export interface Download {
	id: string;
	user: string;
	status: Status;
	process?: ReturnType<typeof spawn>;
	startTime: Date;
	outputDir: string;
}

/**
 * Events emitted by DownloadManager.
 */
export interface StatusChangeEvent {
	id: string;
	user: string;
	status: Status;
}
